name: BowMotion
version: '1.0.1'
main: dev.skippaddin.bowmotion.BowMotion
api-version: '1.21'
softdepend:
  - Essentials
commands:
  BowMotion:
    description: "Commands for the BowMotion plugin."
    permissions:
      BowMotion.command.start:
        description: "Starts the challenge."
      BowMotion.command.stop:
        description: "Ends the challenge and saves the timer."
      BowMotion.command.reset:
        description: "Resets the timer if the game is not running."